### ISSUE TITLE
Documentation styling?

### ISSUE THREAD

**Issue by morficus** [propellant/doctor#1]
The sample output that is [referenced in the documentation](https://github.com/propellant/doctor/raw/master/exampleOutput.png) shows some nicely styled output, but when I run the examples... the output seems quite different.
<img width="780" alt="screen shot 2017-07-18 at 10 48 21 pm" src="https://user-images.githubusercontent.com/718799/28348492-46a0d858-6c0b-11e7-8b03-4836c77d222e.png">

Am I missing something? Or is the intention for the person using PropDoc to style everything them self?

**Comment by pearofducks** [comment]
Yes, this is completely intentional - though I can see how having the option of using a "default" styling is beneficial.

Putting something together I'm confident in releasing will take some time, for the moment you're more than welcome to reference and use as much of [the source for that screenshot](https://prpllnt.io/docs) as you'd like!

**Comment by pearofducks** [comment]
Closed by dbce1c9
