### ISSUE TITLE
Example site doesn't npm run dev

### ISSUE THREAD

**Issue by sirberus** [propellant/doctor#13]
Details:
* Win10 Professional
* Node10
* npm-installed

Steps taken:
* Pull down
* `cd examples`
* `npm install`
* `npm run dev`

It complains that node-sass and propdoc can't be found. After npm installing both packages, the sass message goes away, but the propdoc message remains.

Message:
```
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/Documentation.vue
Module not found: Error: Can't resolve 'propdoc' in 'C:\Users\keenanpx\Desktop\webdev\epicenter-vue\etc\doctor-master\doctor-master\examples\src'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/Documentation.vue 15:0-30
 @ ./src/Documentation.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by pearofducks** [comment]
This is almost definitely caused by something goofy in Windows and [this line](https://github.com/propellant/doctor/blob/master/examples/webpack.config.js#L21). I don't have Windows to be able to resolve though.

You could try removing that line and actually installing _propDoc_ instead of aliasing it.
